### ISSUE TITLE
pip/pypi installation instructions 

### ISSUE THREAD

**Issue by collinanderson** [mathiasertl/fabric#13]
Would be nice to have a link to pypi or have pip install instructions. Thanks!

**Comment by cjw296** [comment]
`pip install Fabric3` really needs to be in the docs? ;-)

**Comment by collinanderson** [comment]
Ahh, I see it. in the README. not sure what docs I was referring to. :)

I think it's not necessarily clear on first glance that "fabric3" is the pypi name. Maybe "fabric3" should be in the description, or maybe the whole repo should be renamed fabric3.

**Comment by mathiasertl** [comment]
It's not quite as simple as "pip install Fabric3" - since you have to uninstall the original Fabric as well (setuptools does not provide a "conflicts" parameter as far as I am aware). 

The README - which show up in the main github page - says this right on top. But if the info is anywhere missing, please let me know!

**Comment by TheJimFactor** [comment]
Thanks for doing the python 3 fork of fabric. I love fabric and it really makes my life easier to have it work with Python 3.

**Comment by mathiasertl** [comment]
Thanks for the roses!

I'm closing the issue now, I think there isn't really an issue remaining?!
